//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DoenaSoft.DVDProfiler.EnhancedPurchaseInfo
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedPurchaseInfo
    {

        private Price originalPriceField;

        private Price shippingCostField;

        private Price creditCardChargeField;

        private Price creditCardFeesField;

        private Price discountField;

        private Price customsFeesField;

        private Text couponTypeField;

        private Text couponCodeField;

        private Price additionalPrice1Field;

        private Price additionalPrice2Field;

        private Date orderDateField;

        private Date shippingDateField;

        private Date deliveryDateField;

        private Date additionalDate1Field;

        private Date additionalDate2Field;

        private InvelosData invelosDataField;

        /// <remarks/>
        public Price OriginalPrice
        {
            get
            {
                return this.originalPriceField;
            }
            set
            {
                this.originalPriceField = value;
            }
        }

        /// <remarks/>
        public Price ShippingCost
        {
            get
            {
                return this.shippingCostField;
            }
            set
            {
                this.shippingCostField = value;
            }
        }

        /// <remarks/>
        public Price CreditCardCharge
        {
            get
            {
                return this.creditCardChargeField;
            }
            set
            {
                this.creditCardChargeField = value;
            }
        }

        /// <remarks/>
        public Price CreditCardFees
        {
            get
            {
                return this.creditCardFeesField;
            }
            set
            {
                this.creditCardFeesField = value;
            }
        }

        /// <remarks/>
        public Price Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }

        /// <remarks/>
        public Price CustomsFees
        {
            get
            {
                return this.customsFeesField;
            }
            set
            {
                this.customsFeesField = value;
            }
        }

        /// <remarks/>
        public Text CouponType
        {
            get
            {
                return this.couponTypeField;
            }
            set
            {
                this.couponTypeField = value;
            }
        }

        /// <remarks/>
        public Text CouponCode
        {
            get
            {
                return this.couponCodeField;
            }
            set
            {
                this.couponCodeField = value;
            }
        }

        /// <remarks/>
        public Price AdditionalPrice1
        {
            get
            {
                return this.additionalPrice1Field;
            }
            set
            {
                this.additionalPrice1Field = value;
            }
        }

        /// <remarks/>
        public Price AdditionalPrice2
        {
            get
            {
                return this.additionalPrice2Field;
            }
            set
            {
                this.additionalPrice2Field = value;
            }
        }

        /// <remarks/>
        public Date OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        /// <remarks/>
        public Date ShippingDate
        {
            get
            {
                return this.shippingDateField;
            }
            set
            {
                this.shippingDateField = value;
            }
        }

        /// <remarks/>
        public Date DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }

        /// <remarks/>
        public Date AdditionalDate1
        {
            get
            {
                return this.additionalDate1Field;
            }
            set
            {
                this.additionalDate1Field = value;
            }
        }

        /// <remarks/>
        public Date AdditionalDate2
        {
            get
            {
                return this.additionalDate2Field;
            }
            set
            {
                this.additionalDate2Field = value;
            }
        }

        /// <remarks/>
        public InvelosData InvelosData
        {
            get
            {
                return this.invelosDataField;
            }
            set
            {
                this.invelosDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Price
    {

        private string denominationTypeField;

        private string denominationDescField;

        private string formattedValueField;

        private string displayNameField;

        private string base64DisplayNameField;

        private float valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationType
        {
            get
            {
                return this.denominationTypeField;
            }
            set
            {
                this.denominationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DenominationDesc
        {
            get
            {
                return this.denominationDescField;
            }
            set
            {
                this.denominationDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormattedValue
        {
            get
            {
                return this.formattedValueField;
            }
            set
            {
                this.formattedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64DisplayName
        {
            get
            {
                return this.base64DisplayNameField;
            }
            set
            {
                this.base64DisplayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile
    {

        private EnhancedPurchaseInfo enhancedPurchaseInfoField;

        private string idField;

        private string titleField;

        /// <remarks/>
        public EnhancedPurchaseInfo EnhancedPurchaseInfo
        {
            get
            {
                return this.enhancedPurchaseInfoField;
            }
            set
            {
                this.enhancedPurchaseInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvelosData
    {

        private Price purchasePriceField;

        private Price sRPField;

        private System.DateTime purchaseDateField;

        private bool purchaseDateFieldSpecified;

        /// <remarks/>
        public Price PurchasePrice
        {
            get
            {
                return this.purchasePriceField;
            }
            set
            {
                this.purchasePriceField = value;
            }
        }

        /// <remarks/>
        public Price SRP
        {
            get
            {
                return this.sRPField;
            }
            set
            {
                this.sRPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime PurchaseDate
        {
            get
            {
                return this.purchaseDateField;
            }
            set
            {
                this.purchaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PurchaseDateSpecified
        {
            get
            {
                return this.purchaseDateFieldSpecified;
            }
            set
            {
                this.purchaseDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date
    {

        private string displayNameField;

        private string base64DisplayNameField;

        private System.DateTime valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64DisplayName
        {
            get
            {
                return this.base64DisplayNameField;
            }
            set
            {
                this.base64DisplayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Text
    {

        private string displayNameField;

        private string base64DisplayNameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64DisplayName
        {
            get
            {
                return this.base64DisplayNameField;
            }
            set
            {
                this.base64DisplayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedPurchaseInfoList
    {

        private Profile[] profilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Profile[] Profiles
        {
            get
            {
                return this.profilesField;
            }
            set
            {
                this.profilesField = value;
            }
        }
    }
}