//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.EnhancedPurchaseInfo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurrencyName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.EnhancedPurchaseInfo.Resources.CurrencyName", typeof(CurrencyName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States (Dollar).
        /// </summary>
        internal static string CURRENCY_0 {
            get {
                return ResourceManager.GetString("CURRENCY_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina (Peso).
        /// </summary>
        internal static string CURRENCY_1 {
            get {
                return ResourceManager.GetString("CURRENCY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong (Dollar).
        /// </summary>
        internal static string CURRENCY_10 {
            get {
                return ResourceManager.GetString("CURRENCY_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland (Krona).
        /// </summary>
        internal static string CURRENCY_11 {
            get {
                return ResourceManager.GetString("CURRENCY_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India (Rupee).
        /// </summary>
        internal static string CURRENCY_12 {
            get {
                return ResourceManager.GetString("CURRENCY_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia (Rupiah).
        /// </summary>
        internal static string CURRENCY_13 {
            get {
                return ResourceManager.GetString("CURRENCY_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel (Shekel).
        /// </summary>
        internal static string CURRENCY_14 {
            get {
                return ResourceManager.GetString("CURRENCY_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan (Yen).
        /// </summary>
        internal static string CURRENCY_15 {
            get {
                return ResourceManager.GetString("CURRENCY_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico (New Peso).
        /// </summary>
        internal static string CURRENCY_16 {
            get {
                return ResourceManager.GetString("CURRENCY_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand (Dollar).
        /// </summary>
        internal static string CURRENCY_17 {
            get {
                return ResourceManager.GetString("CURRENCY_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway (Krone).
        /// </summary>
        internal static string CURRENCY_18 {
            get {
                return ResourceManager.GetString("CURRENCY_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines (Peso).
        /// </summary>
        internal static string CURRENCY_19 {
            get {
                return ResourceManager.GetString("CURRENCY_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (Dollar).
        /// </summary>
        internal static string CURRENCY_2 {
            get {
                return ResourceManager.GetString("CURRENCY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia (Rouble).
        /// </summary>
        internal static string CURRENCY_20 {
            get {
                return ResourceManager.GetString("CURRENCY_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore (Dollar).
        /// </summary>
        internal static string CURRENCY_21 {
            get {
                return ResourceManager.GetString("CURRENCY_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa (Rand).
        /// </summary>
        internal static string CURRENCY_22 {
            get {
                return ResourceManager.GetString("CURRENCY_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea (Won).
        /// </summary>
        internal static string CURRENCY_23 {
            get {
                return ResourceManager.GetString("CURRENCY_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden (Krona).
        /// </summary>
        internal static string CURRENCY_24 {
            get {
                return ResourceManager.GetString("CURRENCY_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland (Franc).
        /// </summary>
        internal static string CURRENCY_25 {
            get {
                return ResourceManager.GetString("CURRENCY_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan (Dollar).
        /// </summary>
        internal static string CURRENCY_26 {
            get {
                return ResourceManager.GetString("CURRENCY_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand (Baht).
        /// </summary>
        internal static string CURRENCY_27 {
            get {
                return ResourceManager.GetString("CURRENCY_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey (1 million Lira).
        /// </summary>
        internal static string CURRENCY_28 {
            get {
                return ResourceManager.GetString("CURRENCY_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia (Ringgit).
        /// </summary>
        internal static string CURRENCY_29 {
            get {
                return ResourceManager.GetString("CURRENCY_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil (Real).
        /// </summary>
        internal static string CURRENCY_3 {
            get {
                return ResourceManager.GetString("CURRENCY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        internal static string CURRENCY_30 {
            get {
                return ResourceManager.GetString("CURRENCY_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary (Forint).
        /// </summary>
        internal static string CURRENCY_31 {
            get {
                return ResourceManager.GetString("CURRENCY_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland (Zloty).
        /// </summary>
        internal static string CURRENCY_32 {
            get {
                return ResourceManager.GetString("CURRENCY_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic (Koruna).
        /// </summary>
        internal static string CURRENCY_33 {
            get {
                return ResourceManager.GetString("CURRENCY_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam (Dong).
        /// </summary>
        internal static string CURRENCY_34 {
            get {
                return ResourceManager.GetString("CURRENCY_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia (Kroon).
        /// </summary>
        internal static string CURRENCY_35 {
            get {
                return ResourceManager.GetString("CURRENCY_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania (New leu).
        /// </summary>
        internal static string CURRENCY_36 {
            get {
                return ResourceManager.GetString("CURRENCY_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia (Koruna).
        /// </summary>
        internal static string CURRENCY_37 {
            get {
                return ResourceManager.GetString("CURRENCY_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada (Dollar).
        /// </summary>
        internal static string CURRENCY_4 {
            get {
                return ResourceManager.GetString("CURRENCY_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile (Peso).
        /// </summary>
        internal static string CURRENCY_5 {
            get {
                return ResourceManager.GetString("CURRENCY_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China (Renminbi).
        /// </summary>
        internal static string CURRENCY_6 {
            get {
                return ResourceManager.GetString("CURRENCY_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark (Krone).
        /// </summary>
        internal static string CURRENCY_7 {
            get {
                return ResourceManager.GetString("CURRENCY_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe (Euro).
        /// </summary>
        internal static string CURRENCY_8 {
            get {
                return ResourceManager.GetString("CURRENCY_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Britain (Pound).
        /// </summary>
        internal static string CURRENCY_9 {
            get {
                return ResourceManager.GetString("CURRENCY_9", resourceCulture);
            }
        }
    }
}
